### ISSUE TITLE
Register not working

### ISSUE THREAD

**Issue by Ronho** [michael-spengler/price-predictor-wwi19dsa#16]
Registrierung aktuell nicht möglich.

- **URL**: http://3.131.4.23:5000/signup
- **Body**:
>{
    "email": "asdasdasd",
    "firstName": "asdasd",
    "lastname": "name",
    "password": "Asasdasdasdas",
    "username": "asdasd",
    "street": "asdasd",
    "plz": "asdsadsad",
    "city": "asdsad",
    "country": "asdasdasdasdasdasd"
}

- **Error**: 500 INTERNAL SERVER ERROR [response.pdf](https://github.com/michael-spengler/price-predictor-wwi19dsa/files/5714320/response.pdf)

**Comment by Ronho** [comment]
Das könnte daran liegen, dass das UserModel in der server.py einen Attribute mit nullable=false hat, die jedoch bei der Registrierung bzw. der User Erstellung im Backend nicht übernommen werden.

**Comment by pfeeerdi** [comment]
@Irish-77 @Ronho should be fixed from my end now!
